sudo: false
language: java
jdk:
  - oraclejdk8
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    
before_install:
 - chmod +x gradlew

script: "./gradlew -q  clean test assemble"

notifications:
  slack:
    rooms:
      - nevohq:$SLACKTOKEN#general
  
before_deploy:
  - export RELEASE_FILE=$(ls build/libs/RestAssuredExample-*.jar)
jobs:
  include:
    - script: "./gradlew -q  clean test"
    - script: "./gradlew -q  clean assemble"
    - stage: GitHub Release
      script: echo "Deploying $RELEASE_FILE to GitHub releases ..."
      deploy:
        provider: releases
        api_key: $GTOKEN
        file:  $RELEASE_FILE
        skip_cleanup: true
        overwrite: true
        on:
          tags: true
